"""SOAP bridge: an httpx transport that turns REST/JSON calls generated by
FastMCP's OpenAPI integration into literal SOAP calls.

FastMCP tool call -> POST {base}/operations/{op} (JSON)
    -> [this transport] JSON -> SOAP envelope (metadata from x-soap + xml
       annotations in the spec) -> real SOAP endpoint -> XML response ->
       JSON (shaped by the response schema) -> httpx.Response(200, json)

The container image stays fixed: swapping the OpenAPI spec (ConfigMap) is
enough to expose a different SOAP service as MCP.
"""
from __future__ import annotations

import dataclasses
import json
import logging
import math
import os
from typing import Any

import httpx
from lxml import etree

from .checks import _component_schemas
from .openapi import schema_ref_name

logger = logging.getLogger("spec2openapi")

SOAP_ENV_NS = {
    "1.1": "http://schemas.xmlsoap.org/soap/envelope/",
    "1.2": "http://www.w3.org/2003/05/soap-envelope",
}
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
WSSE_NS = (
    "http://docs.oasis-open.org/wss/2004/01/"
    "oasis-200401-wss-wssecurity-secext-1.0.xsd"
)
PASSWORD_TEXT = (
    "http://docs.oasis-open.org/wss/2004/01/"
    "oasis-200401-wss-username-token-profile-1.0#PasswordText"
)


def _soap_version(xsoap: dict[str, Any]) -> str:
    """Normalize x-soap.soapVersion to the "1.1"/"1.2" text every lookup
    here keys on. A hand-edited YAML spec can turn this into something
    other than a clean string: an unquoted `soapVersion: 1.2` parses as
    the float 1.2 (str(1.2) == "1.2", so this round-trips it), and a
    missing/null value falls back to "1.1" like the rest of the bridge
    assumes."""
    v = xsoap.get("soapVersion")
    return str(v) if v is not None else "1.1"


_FALSEY = {"0", "false", "no", "off"}
_TRUTHY = {"1", "true", "yes", "on"}


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    # an empty value means "leave the default" (as for _env_float and the
    # string vars); it must never read as False and disable TLS verification
    if raw is None or not raw.strip():
        return default
    v = raw.strip().lower()
    if v in _FALSEY:
        return False
    if v in _TRUTHY:
        return True
    logger.warning("env %s=%r not recognized as boolean; using %s",
                   name, raw, default)
    return default


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return float(raw)
    except ValueError:
        logger.warning("env %s=%r is not a number; using %s",
                       name, raw, default)
        return default


def _env_json_object(name: str) -> dict[str, Any] | None:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return None
    try:
        value = json.loads(raw)
    except json.JSONDecodeError as exc:
        logger.warning("env %s is not valid JSON (%s); ignoring", name, exc)
        return None
    if not isinstance(value, dict):
        logger.warning("env %s must be a JSON object; ignoring", name)
        return None
    return value


@dataclasses.dataclass
class BridgeOptions:
    """Runtime options, typically injected via env vars in the container."""

    endpoint: str | None = None  # override the WSDL-declared endpoint
    username: str | None = None
    password: str | None = None
    auth: str | None = None  # None | "basic" | "wsse"
    timeout: float = 30.0
    verify: bool = True
    headers: dict[str, str] | None = None  # extra *HTTP* headers on the POST
    trust_env: bool = True  # honor HTTP(S)_PROXY / NO_PROXY env vars
    # values for declared soap:header parts (x-soap.headers[]), keyed by
    # either the WSDL part name or the header element name — not to be
    # confused with `headers` above (plain HTTP headers, not SOAP XML).
    # There is no per-call source for these (tool arguments never carry
    # them, by design: see openapi.py's "supplied by the runtime" note),
    # so they are runtime/deployment-level configuration.
    soap_headers: dict[str, Any] | None = None
    # internal: (operation, header) pairs already warned about via
    # _warn_missing_header, so a long-lived bridge logs each gap once
    _warned_missing_headers: set[str] = dataclasses.field(
        default_factory=set, repr=False, compare=False,
    )

    @classmethod
    def from_env(cls) -> "BridgeOptions":
        return cls(
            endpoint=os.getenv("SPEC2OPENAPI_ENDPOINT") or None,
            username=os.getenv("SPEC2OPENAPI_USERNAME") or None,
            password=os.getenv("SPEC2OPENAPI_PASSWORD") or None,
            auth=os.getenv("SPEC2OPENAPI_AUTH") or None,
            timeout=_env_float("SPEC2OPENAPI_TIMEOUT", 30.0),
            verify=_env_bool("SPEC2OPENAPI_VERIFY", True),
            trust_env=_env_bool("SPEC2OPENAPI_TRUST_ENV", True),
            soap_headers=_env_json_object("SPEC2OPENAPI_SOAP_HEADERS"),
        )


def _basic_auth(options: BridgeOptions) -> tuple[str, str] | None:
    """The (username, password) tuple for httpx's `auth=` kwarg, or None
    when basic auth isn't configured."""
    if options.auth == "basic" and options.username is not None:
        return (options.username, options.password or "")
    return None


def _client_kwargs(options: BridgeOptions) -> dict[str, Any]:
    """httpx.AsyncClient kwargs derived from BridgeOptions: auth, timeout,
    TLS verify, extra headers, proxy-env trust. Shared by the SOAP
    bridge's own outbound client below and the plain-REST client
    server.py builds for non-SOAP specs (a caller adds base_url itself —
    only the REST client needs one; the bridge posts to a per-call
    endpoint instead)."""
    return {
        "auth": _basic_auth(options),
        "timeout": options.timeout,
        "verify": options.verify,
        "headers": options.headers or {},
        "trust_env": options.trust_env,
    }


# --------------------------------------------------------------------------
# spec indexing helpers
# --------------------------------------------------------------------------


class _SpecIndex:
    def __init__(self, spec: dict[str, Any]):
        self.spec = spec
        # components (or components.schemas) may be null (`components:`
        # with no value) rather than absent; same class of bug already
        # fixed for cmd_validate — reuse its null-tolerant lookup
        self.components: dict[str, Any] = _component_schemas(spec)
        self.ops: dict[str, dict[str, Any]] = {}
        for path, item in (spec.get("paths") or {}).items():
            post = (item or {}).get("post") or {}
            xsoap = post.get("x-soap")
            if not xsoap:
                continue
            req = (
                post.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            out = (
                post.get("responses", {})
                .get("200", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            self.ops[path] = {"x-soap": xsoap, "input": req, "output": out}

    def deref(self, schema: dict[str, Any] | None) -> dict[str, Any]:
        """Resolve $ref / single-allOf wrappers, keeping xml annotations."""
        if not schema:
            return {}
        seen = 0
        xml = schema.get("xml")
        while seen < 32:
            if "$ref" in schema:
                ref = schema["$ref"]
                # every real ref here is '#/components/schemas/NAME'
                # (schema.py never emits anything deeper); fall back to
                # the old last-segment extraction for anything else so
                # behavior is unchanged for a non-schemas/malformed ref
                name = schema_ref_name(ref)
                if name is None:
                    name = ref.rsplit("/", 1)[-1]
                schema = self.components.get(name, {})
            elif "allOf" in schema and len(schema["allOf"]) == 1:
                inner = schema["allOf"][0]
                merged = dict(inner)
                for k, v in schema.items():
                    if k != "allOf":
                        merged.setdefault(k, v)
                schema = merged
            else:
                break
            seen += 1
        if xml and "xml" not in schema:
            schema = dict(schema)
            schema["xml"] = xml
        return schema


# --------------------------------------------------------------------------
# JSON -> SOAP envelope
# --------------------------------------------------------------------------


def _to_text(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _write_value(parent: etree._Element, tag: etree.QName | str, schema: dict,
                 value: Any, index: _SpecIndex) -> None:
    el = etree.SubElement(parent, tag)
    if value is None:
        el.set(etree.QName(XSI_NS, "nil"), "true")
        return
    schema = index.deref(schema)
    if schema.get("type") == "object" or "properties" in schema:
        _write_object(el, schema, value, index)
    elif isinstance(value, (dict,)):
        _write_object(el, schema, value, index)
    else:
        el.text = _to_text(value)


def _write_substitution(parent: etree._Element, sub: dict, value: Any,
                        prop: str, index: _SpecIndex) -> None:
    """Serialize a substitution-group value: {"creditCard": {...}} names
    the wire element itself; the head element never appears."""
    entries = {m["element"]: m for m in sub.get("members", [])}
    if not (isinstance(value, dict) and len(value) == 1):
        raise ValueError(
            f"property '{prop}' expects exactly one of "
            f"{sorted(entries)} as its single key"
        )
    (member, inner), = value.items()
    entry = entries.get(member)
    if entry is None:
        raise ValueError(
            f"property '{prop}': unknown substitution element '{member}' "
            f"(expected one of {sorted(entries)})"
        )
    ns = entry.get("namespace")
    tag = etree.QName(ns, entry["element"]) if ns else entry["element"]
    _write_value(parent, tag, {"$ref": entry["schema"]}, inner, index)


def _write_object(parent: etree._Element, schema: dict, data: Any,
                  index: _SpecIndex) -> None:
    schema = index.deref(schema)
    props: dict[str, Any] = schema.get("properties", {})
    if not isinstance(data, dict):
        parent.text = _to_text(data)
        return

    # attributes first
    for name, pschema in props.items():
        pd = index.deref(pschema)
        xml = pd.get("xml") or pschema.get("xml") or {}
        if xml.get("attribute") and name in data and data[name] is not None:
            parent.set(xml.get("name", name), _to_text(data[name]))

    # elements in schema (=XSD sequence) order
    for name, pschema in props.items():
        pd = index.deref(pschema)
        xml = pd.get("xml") or pschema.get("xml") or {}
        if xml.get("attribute"):
            continue
        if name not in data:
            continue
        value = data[name]
        if xml.get("x-text"):  # xsd:simpleContent text value
            parent.text = _to_text(value) if value is not None else None
            continue
        local = xml.get("name", name)
        ns = xml.get("namespace")
        tag = etree.QName(ns, local) if ns else local
        if pd.get("type") == "array":
            items_schema = pd.get("items", {})
            items_sub = index.deref(items_schema).get("x-soap-substitution")
            for item in value if isinstance(value, list) else [value]:
                if items_sub:
                    _write_substitution(parent, items_sub, item, name, index)
                else:
                    _write_value(parent, tag, items_schema, item, index)
        elif pd.get("x-soap-substitution"):
            _write_substitution(
                parent, pd["x-soap-substitution"], value, name, index
            )
        else:
            _write_value(parent, tag, pd, value, index)

    for name in data:
        if name not in props:
            logger.debug("payload key %r not in schema; ignored", name)


def _choice_violations(schema: dict[str, Any], data: Any) -> list[str]:
    """Enforce x-soap-choice on the payload: at most one *branch* per
    group, and exactly one when the group is required.

    A `members[]` entry is normally a bare property name (one branch),
    but may also be a list of names — a branch that is itself an
    xsd:sequence of 2+ elements (#141 B2). Those names belong together,
    so the branch counts as "chosen" when any of its own names is set,
    and setting several of them together is not a violation; only
    choosing more than one *branch* (or none, when required) is."""
    if not isinstance(data, dict):
        return []
    errors: list[str] = []
    for group in schema.get("x-soap-choice", []) or []:
        members = group.get("members", [])
        chosen: list[Any] = []   # branch entries with >=1 name present
        present: list[str] = []  # every individual name actually set
        for m in members:
            names = m if isinstance(m, list) else [m]
            hit = [n for n in names
                  if isinstance(n, str) and data.get(n) is not None]
            if hit:
                chosen.append(m)
                present.extend(hit)
        if len(chosen) > 1:
            errors.append(
                f"at most one of {members} may be set (got {present})"
            )
        elif group.get("required") and not chosen:
            errors.append(f"exactly one of {members} is required")
    return errors


def _lookup_soap_header(soap_headers: dict[str, Any] | None,
                        hmeta: dict[str, Any]) -> tuple[Any, bool]:
    """Look up a declared soap:header's value: by WSDL part name first,
    then by element name. Returns (value, True) even for an explicit None
    (rendered as xsi:nil), or (None, False) if nothing was supplied."""
    if not soap_headers:
        return None, False
    for key in (hmeta.get("part"), hmeta.get("element")):
        if key is not None and key in soap_headers:
            return soap_headers[key], True
    return None, False


def _warn_missing_header(options: BridgeOptions, xsoap: dict[str, Any],
                         hmeta: dict[str, Any]) -> None:
    """Log once per (operation, header) that a declared header has no
    configured value, instead of silently sending the call without it."""
    key = f"{xsoap.get('operation')}:{hmeta.get('part') or hmeta.get('element')}"
    if key in options._warned_missing_headers:
        return
    options._warned_missing_headers.add(key)
    logger.warning(
        "operation %s declares soap:header part=%r (element %s) but "
        "BridgeOptions.soap_headers / SPEC2OPENAPI_SOAP_HEADERS supplies "
        "no value for it; sending the request without this header",
        xsoap.get("operation"), hmeta.get("part"), hmeta.get("element"),
    )


def build_envelope(op: dict[str, Any], payload: dict[str, Any],
                   index: _SpecIndex, options: BridgeOptions) -> bytes:
    xsoap = op["x-soap"]
    env_ns = SOAP_ENV_NS.get(_soap_version(xsoap), SOAP_ENV_NS["1.1"])
    nsmap = {"soapenv": env_ns}
    envelope = etree.Element(etree.QName(env_ns, "Envelope"), nsmap=nsmap)
    header = None

    if options.auth == "wsse" and options.username is not None:
        header = etree.SubElement(envelope, etree.QName(env_ns, "Header"))
        security = etree.SubElement(
            header, etree.QName(WSSE_NS, "Security"), nsmap={"wsse": WSSE_NS}
        )
        security.set(etree.QName(env_ns, "mustUnderstand"), "1")
        token = etree.SubElement(security, etree.QName(WSSE_NS, "UsernameToken"))
        user = etree.SubElement(token, etree.QName(WSSE_NS, "Username"))
        user.text = options.username
        pwd = etree.SubElement(token, etree.QName(WSSE_NS, "Password"))
        pwd.set("Type", PASSWORD_TEXT)
        pwd.text = options.password or ""

    for hmeta in xsoap.get("headers") or []:
        value, supplied = _lookup_soap_header(options.soap_headers, hmeta)
        if not supplied:
            _warn_missing_header(options, xsoap, hmeta)
            continue
        if header is None:
            header = etree.SubElement(envelope, etree.QName(env_ns, "Header"))
        local = hmeta.get("element") or hmeta.get("part") or "Header"
        ns = hmeta.get("namespace")
        tag = etree.QName(ns, local) if ns else local
        _write_value(header, tag, {"$ref": hmeta["schema"]}, value, index)

    body = etree.SubElement(envelope, etree.QName(env_ns, "Body"))
    in_meta = xsoap.get("input", {})
    ns = in_meta.get("namespace")
    local = in_meta.get("element", xsoap.get("operation", "Request"))
    # use a *prefixed* namespace: unqualified children (rpc parts,
    # elementFormDefault="unqualified") must not inherit a default ns
    root_nsmap = {"tns": ns} if ns else None
    root = etree.SubElement(
        body, etree.QName(ns, local) if ns else local, nsmap=root_nsmap
    )
    _write_object(root, index.deref(op.get("input", {})), payload or {}, index)

    return etree.tostring(envelope, xml_declaration=True, encoding="utf-8")


# --------------------------------------------------------------------------
# SOAP response -> JSON
# --------------------------------------------------------------------------


def _localname(el: etree._Element) -> str:
    try:
        return etree.QName(el).localname
    except Exception:
        return str(el.tag)


def _coerce(text: str | None, schema: dict[str, Any]) -> Any:
    if text is None:
        return None
    t = schema.get("type")
    if isinstance(t, list):
        # OpenAPI 3.1 nullable scalar, e.g. to_openapi_31's ["integer",
        # "null"]: coerce against the first non-null member, if any
        t = next((x for x in t if x != "null"), None)
    s = text.strip()
    try:
        if t == "integer":
            return int(s)
        if t == "number":
            v = float(s)
            # xsd NaN/INF/-INF parse fine but aren't valid JSON; httpx's
            # encoder would emit a bare (invalid) token for them, so keep
            # the original text instead of a non-finite float
            return v if math.isfinite(v) else text
        if t == "boolean":
            low = s.lower()
            if low in ("true", "1"):
                return True
            if low in ("false", "0"):
                return False
            return text  # non-canonical: don't silently coerce to False
    except ValueError:
        return text
    return text if t == "string" else (text if s == "" else s)


def _read_object(el: etree._Element, schema: dict[str, Any],
                 index: _SpecIndex) -> Any:
    schema = index.deref(schema)
    props: dict[str, Any] = schema.get("properties", {})
    if not props:
        # no schema knowledge: return text or shallow dict of children
        children = [c for c in el if isinstance(c.tag, str)]
        if not children:
            return el.text
        out: dict[str, Any] = {}
        for c in children:
            name = _localname(c)
            val = _read_object(c, {}, index)
            if name in out:
                if not isinstance(out[name], list):
                    out[name] = [out[name]]
                out[name].append(val)
            else:
                out[name] = val
        return out

    result: dict[str, Any] = {}
    children = [c for c in el if isinstance(c.tag, str)]
    by_name: dict[str, list[etree._Element]] = {}
    for c in children:
        by_name.setdefault(_localname(c), []).append(c)

    for name, pschema in props.items():
        pd = index.deref(pschema)
        xml = pd.get("xml") or (pschema.get("xml") if isinstance(pschema, dict) else None) or {}
        local = xml.get("name", name)
        if xml.get("attribute"):
            v = el.get(local)
            if v is not None:
                result[name] = _coerce(v, pd)
            continue
        if xml.get("x-text"):  # xsd:simpleContent text value
            result[name] = _coerce(el.text, pd)
            continue
        sub = pd.get("x-soap-substitution")
        items_schema = None
        if pd.get("type") == "array":
            items_schema = index.deref(pd.get("items", {}))
            sub = items_schema.get("x-soap-substitution") or sub
        if sub:
            # the wire carries the member element's own name; wrap it back
            # into the self-describing {"member": {...}} form
            entries = {m["element"]: m for m in sub.get("members", [])}
            found = [
                (_localname(c), c) for c in children
                if _localname(c) in entries
            ]
            wrapped = [
                {ln: _read_node(c, {"$ref": entries[ln]["schema"]}, index)}
                for ln, c in found
            ]
            if pd.get("type") == "array":
                result[name] = wrapped
            elif wrapped:
                result[name] = wrapped[0]
            continue
        nodes = by_name.get(local, [])
        if pd.get("type") == "array":
            result[name] = [_read_node(n, items_schema, index) for n in nodes]
        elif nodes:
            result[name] = _read_node(nodes[0], pd, index)
    return result


def _read_node(node: etree._Element, schema: dict[str, Any],
               index: _SpecIndex) -> Any:
    if node.get(etree.QName(XSI_NS, "nil")) in ("true", "1"):
        return None
    schema = index.deref(schema)
    if schema.get("type") == "object" or "properties" in schema:
        return _read_object(node, schema, index)
    return _coerce(node.text, schema)


def parse_fault(body: etree._Element, env_ns: str) -> dict[str, Any] | None:
    fault = body.find(f"{{{env_ns}}}Fault")
    if fault is None:
        return None
    if env_ns == SOAP_ENV_NS["1.2"]:
        code = fault.findtext(f"{{{env_ns}}}Code/{{{env_ns}}}Value") or ""
        reason = fault.findtext(f"{{{env_ns}}}Reason/{{{env_ns}}}Text") or ""
        detail_el = fault.find(f"{{{env_ns}}}Detail")
    else:
        code = fault.findtext("faultcode") or ""
        reason = fault.findtext("faultstring") or ""
        detail_el = fault.find("detail")
    detail = ""
    if detail_el is not None:
        detail = etree.tostring(detail_el, encoding="unicode")
    return {"faultcode": code, "faultstring": reason, "detail": detail}


def _http_error(http_status: int, content: bytes) -> tuple[int, dict[str, Any]]:
    return 502, {
        "faultcode": "spec2openapi.HTTPError",
        "faultstring": f"endpoint returned HTTP {http_status}",
        "detail": content[:2000].decode("utf-8", "replace"),
    }


def _http_fault(http_status: int, content: bytes) -> tuple[int, dict[str, Any]]:
    """Like _http_error, but for a body that parsed as a well-formed
    (non-Fault) SOAP envelope: legible enough to trust, so the endpoint's
    actual HTTP status is reported instead of a generic 502."""
    return http_status, {
        "faultcode": "spec2openapi.HTTPError",
        "faultstring": (
            f"endpoint returned HTTP {http_status} "
            "(response body parsed but contained no SOAP Fault)"
        ),
        "detail": content[:2000].decode("utf-8", "replace"),
    }


def parse_response(content: bytes, op: dict[str, Any],
                   index: _SpecIndex,
                   http_status: int = 200) -> tuple[int, dict[str, Any]]:
    """Returns (mapped_status, json_payload). http_status is the transport
    status code, used to give sensible errors for empty/non-XML bodies."""
    xsoap = op["x-soap"]
    is_one_way = not xsoap.get("output")
    env_ns = SOAP_ENV_NS.get(_soap_version(xsoap), SOAP_ENV_NS["1.1"])

    if not content or not content.strip():
        # empty body: a one-way call with a 2xx succeeded; otherwise the
        # HTTP status carries the real story
        if http_status >= 400:
            return _http_error(http_status, content)
        if is_one_way:
            return 200, {}
        return 502, {
            "faultcode": "spec2openapi.EmptyResponse",
            "faultstring": f"endpoint returned an empty body (HTTP {http_status})",
            "detail": "",
        }
    try:
        # endpoint responses are untrusted: no entities, DTDs, or network
        parser = etree.XMLParser(resolve_entities=False, load_dtd=False,
                                 no_network=True, huge_tree=False)
        tree = etree.fromstring(content, parser=parser)
    except Exception as exc:
        if http_status >= 400:
            return _http_error(http_status, content)
        return 502, {
            "faultcode": "spec2openapi.InvalidXML",
            "faultstring": f"endpoint returned non-XML response: {exc}",
            "detail": content[:2000].decode("utf-8", "replace"),
        }
    body = tree.find(f"{{{env_ns}}}Body")
    if body is None:
        # tolerate the other soap version's namespace
        for alt in SOAP_ENV_NS.values():
            body = tree.find(f"{{{alt}}}Body")
            if body is not None:
                env_ns = alt
                break
    if body is None:
        if http_status >= 400:
            return _http_error(http_status, content)
        return 502, {
            "faultcode": "spec2openapi.NoBody",
            "faultstring": "no SOAP Body found in response",
            "detail": "",
        }

    fault = parse_fault(body, env_ns)
    if fault is not None:
        return 500, fault
    if http_status >= 400:
        # the body parsed as an envelope but carried no Fault: an upstream
        # proxy/gateway can still return an error status with a templated
        # non-Fault body, and the operation never actually ran
        return _http_fault(http_status, content)

    out_meta = xsoap.get("output") or {}
    expected = out_meta.get("element")
    root = None
    for c in body:
        if not isinstance(c.tag, str):
            continue
        if expected is None or _localname(c) == expected:
            root = c
            break
    if root is None:
        root = next((c for c in body if isinstance(c.tag, str)), None)
    if root is None:
        return 200, {}

    out_schema = index.deref(op.get("output", {}))
    data = _read_object(root, out_schema, index)
    if not isinstance(data, dict):
        data = {"value": data}
    return 200, data


# --------------------------------------------------------------------------
# the transport
# --------------------------------------------------------------------------


def _soap_request_headers(xsoap: dict[str, Any]) -> dict[str, str]:
    """Content-Type / SOAPAction for the outbound POST, from x-soap
    soapAction/soapVersion. Both are trusted-but-verify: a hand-edited
    YAML spec can supply `soapAction: null` (must not become the literal
    string "None") or an unquoted `soapVersion: 1.2` (a float, normalized
    by _soap_version)."""
    action = xsoap.get("soapAction") or ""
    if _soap_version(xsoap) == "1.2":
        ct = "application/soap+xml; charset=utf-8"
        if action:
            ct += f'; action="{action}"'
        return {"Content-Type": ct}
    return {
        "Content-Type": "text/xml; charset=utf-8",
        "SOAPAction": f'"{action}"',
    }


class SoapBridgeTransport(httpx.AsyncBaseTransport):
    """httpx transport that answers FastMCP's REST calls by calling SOAP."""

    def __init__(self, spec: dict[str, Any], options: BridgeOptions | None = None):
        self.index = _SpecIndex(spec)
        self.options = options or BridgeOptions.from_env()
        self._client = httpx.AsyncClient(**_client_kwargs(self.options))

    async def aclose(self) -> None:
        await self._client.aclose()

    def _json_response(self, request: httpx.Request, status: int,
                       payload: dict[str, Any]) -> httpx.Response:
        return httpx.Response(status, json=payload, request=request)

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        path = request.url.path
        op = self.index.ops.get(path)
        if op is None:
            return self._json_response(
                request, 404,
                {"faultcode": "spec2openapi.UnknownOperation",
                 "faultstring": f"no x-soap operation registered for path {path}",
                 "detail": ""},
            )
        raw = request.read()
        try:
            payload = json.loads(raw) if raw else {}
        except json.JSONDecodeError as exc:
            return self._json_response(
                request, 400,
                {"faultcode": "spec2openapi.BadRequest",
                 "faultstring": f"invalid JSON body: {exc}", "detail": ""},
            )

        xsoap = op["x-soap"]
        endpoint = self.options.endpoint or xsoap.get("endpoint")
        if not endpoint:
            return self._json_response(
                request, 502,
                {"faultcode": "spec2openapi.NoEndpoint",
                 "faultstring": "no SOAP endpoint configured "
                                "(x-soap.endpoint / SPEC2OPENAPI_ENDPOINT)",
                 "detail": ""},
            )

        violations = _choice_violations(
            self.index.deref(op.get("input", {})), payload
        )
        if violations:
            return self._json_response(
                request, 400,
                {"faultcode": "spec2openapi.ChoiceViolation",
                 "faultstring": "; ".join(violations), "detail": ""},
            )

        try:
            envelope = build_envelope(op, payload, self.index, self.options)
        except ValueError as exc:  # e.g. malformed substitution wrapper
            return self._json_response(
                request, 400,
                {"faultcode": "spec2openapi.BadRequest",
                 "faultstring": str(exc), "detail": ""},
            )
        headers = _soap_request_headers(xsoap)

        try:
            soap_resp = await self._client.post(
                endpoint, content=envelope, headers=headers
            )
        except httpx.HTTPError as exc:
            return self._json_response(
                request, 502,
                {"faultcode": "spec2openapi.TransportError",
                 "faultstring": f"SOAP endpoint unreachable: {exc}", "detail": ""},
            )

        status, data = parse_response(
            soap_resp.content, op, self.index, soap_resp.status_code
        )
        return self._json_response(request, status, data)
