"""SOAP bridge: an httpx transport that turns REST/JSON calls generated by
FastMCP's OpenAPI integration into literal SOAP calls.

FastMCP tool call -> POST {base}/operations/{op} (JSON)
    -> [this transport] JSON -> SOAP envelope (metadata from x-soap + xml
       annotations in the spec) -> real SOAP endpoint -> XML response ->
       JSON (shaped by the response schema) -> httpx.Response(200, json)

The container image stays fixed: swapping the OpenAPI spec (ConfigMap) is
enough to expose a different SOAP service as MCP.
"""
from __future__ import annotations

import dataclasses
import json
import logging
import os
from typing import Any

import httpx
from lxml import etree

logger = logging.getLogger("spec2openapi")

SOAP_ENV_NS = {
    "1.1": "http://schemas.xmlsoap.org/soap/envelope/",
    "1.2": "http://www.w3.org/2003/05/soap-envelope",
}
XSI_NS = "http://www.w3.org/2001/XMLSchema-instance"
WSSE_NS = (
    "http://docs.oasis-open.org/wss/2004/01/"
    "oasis-200401-wss-wssecurity-secext-1.0.xsd"
)
PASSWORD_TEXT = (
    "http://docs.oasis-open.org/wss/2004/01/"
    "oasis-200401-wss-username-token-profile-1.0#PasswordText"
)


_FALSEY = {"0", "false", "no", "off", ""}
_TRUTHY = {"1", "true", "yes", "on"}


def _env_bool(name: str, default: bool) -> bool:
    raw = os.getenv(name)
    if raw is None:
        return default
    v = raw.strip().lower()
    if v in _FALSEY:
        return False
    if v in _TRUTHY:
        return True
    logger.warning("env %s=%r not recognized as boolean; using %s",
                   name, raw, default)
    return default


def _env_float(name: str, default: float) -> float:
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return default
    try:
        return float(raw)
    except ValueError:
        logger.warning("env %s=%r is not a number; using %s",
                       name, raw, default)
        return default


@dataclasses.dataclass
class BridgeOptions:
    """Runtime options, typically injected via env vars in the container."""

    endpoint: str | None = None  # override the WSDL-declared endpoint
    username: str | None = None
    password: str | None = None
    auth: str | None = None  # None | "basic" | "wsse"
    timeout: float = 30.0
    verify: bool = True
    headers: dict[str, str] | None = None
    trust_env: bool = True  # honor HTTP(S)_PROXY / NO_PROXY env vars

    @classmethod
    def from_env(cls) -> "BridgeOptions":
        return cls(
            endpoint=os.getenv("SPEC2OPENAPI_ENDPOINT") or None,
            username=os.getenv("SPEC2OPENAPI_USERNAME") or None,
            password=os.getenv("SPEC2OPENAPI_PASSWORD") or None,
            auth=os.getenv("SPEC2OPENAPI_AUTH") or None,
            timeout=_env_float("SPEC2OPENAPI_TIMEOUT", 30.0),
            verify=_env_bool("SPEC2OPENAPI_VERIFY", True),
            trust_env=_env_bool("SPEC2OPENAPI_TRUST_ENV", True),
        )


# --------------------------------------------------------------------------
# spec indexing helpers
# --------------------------------------------------------------------------


class _SpecIndex:
    def __init__(self, spec: dict[str, Any]):
        self.spec = spec
        self.components: dict[str, Any] = spec.get("components", {}).get("schemas", {})
        self.ops: dict[str, dict[str, Any]] = {}
        for path, item in spec.get("paths", {}).items():
            post = (item or {}).get("post") or {}
            xsoap = post.get("x-soap")
            if not xsoap:
                continue
            req = (
                post.get("requestBody", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            out = (
                post.get("responses", {})
                .get("200", {})
                .get("content", {})
                .get("application/json", {})
                .get("schema", {})
            )
            self.ops[path] = {"x-soap": xsoap, "input": req, "output": out}

    def deref(self, schema: dict[str, Any] | None) -> dict[str, Any]:
        """Resolve $ref / single-allOf wrappers, keeping xml annotations."""
        if not schema:
            return {}
        seen = 0
        xml = schema.get("xml")
        while seen < 32:
            if "$ref" in schema:
                name = schema["$ref"].rsplit("/", 1)[-1]
                schema = self.components.get(name, {})
            elif "allOf" in schema and len(schema["allOf"]) == 1:
                inner = schema["allOf"][0]
                merged = dict(inner)
                for k, v in schema.items():
                    if k != "allOf":
                        merged.setdefault(k, v)
                schema = merged
            else:
                break
            seen += 1
        if xml and "xml" not in schema:
            schema = dict(schema)
            schema["xml"] = xml
        return schema


# --------------------------------------------------------------------------
# JSON -> SOAP envelope
# --------------------------------------------------------------------------


def _to_text(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


def _write_value(parent: etree._Element, tag: etree.QName | str, schema: dict,
                 value: Any, index: _SpecIndex) -> None:
    el = etree.SubElement(parent, tag)
    if value is None:
        el.set(etree.QName(XSI_NS, "nil"), "true")
        return
    schema = index.deref(schema)
    if schema.get("type") == "object" or "properties" in schema:
        _write_object(el, schema, value, index)
    elif isinstance(value, (dict,)):
        _write_object(el, schema, value, index)
    else:
        el.text = _to_text(value)


def _write_substitution(parent: etree._Element, sub: dict, value: Any,
                        prop: str, index: _SpecIndex) -> None:
    """Serialize a substitution-group value: {"creditCard": {...}} names
    the wire element itself; the head element never appears."""
    entries = {m["element"]: m for m in sub.get("members", [])}
    if not (isinstance(value, dict) and len(value) == 1):
        raise ValueError(
            f"property '{prop}' expects exactly one of "
            f"{sorted(entries)} as its single key"
        )
    (member, inner), = value.items()
    entry = entries.get(member)
    if entry is None:
        raise ValueError(
            f"property '{prop}': unknown substitution element '{member}' "
            f"(expected one of {sorted(entries)})"
        )
    ns = entry.get("namespace")
    tag = etree.QName(ns, entry["element"]) if ns else entry["element"]
    _write_value(parent, tag, {"$ref": entry["schema"]}, inner, index)


def _write_object(parent: etree._Element, schema: dict, data: Any,
                  index: _SpecIndex) -> None:
    schema = index.deref(schema)
    props: dict[str, Any] = schema.get("properties", {})
    if not isinstance(data, dict):
        parent.text = _to_text(data)
        return

    # attributes first
    for name, pschema in props.items():
        pd = index.deref(pschema)
        xml = pd.get("xml") or pschema.get("xml") or {}
        if xml.get("attribute") and name in data and data[name] is not None:
            parent.set(xml.get("name", name), _to_text(data[name]))

    # elements in schema (=XSD sequence) order
    for name, pschema in props.items():
        pd = index.deref(pschema)
        xml = pd.get("xml") or pschema.get("xml") or {}
        if xml.get("attribute"):
            continue
        if name not in data:
            continue
        value = data[name]
        if xml.get("x-text"):  # xsd:simpleContent text value
            parent.text = _to_text(value) if value is not None else None
            continue
        local = xml.get("name", name)
        ns = xml.get("namespace")
        tag = etree.QName(ns, local) if ns else local
        if pd.get("type") == "array":
            items_schema = pd.get("items", {})
            items_sub = index.deref(items_schema).get("x-soap-substitution")
            for item in value if isinstance(value, list) else [value]:
                if items_sub:
                    _write_substitution(parent, items_sub, item, name, index)
                else:
                    _write_value(parent, tag, items_schema, item, index)
        elif pd.get("x-soap-substitution"):
            _write_substitution(
                parent, pd["x-soap-substitution"], value, name, index
            )
        else:
            _write_value(parent, tag, pd, value, index)

    for name in data:
        if name not in props:
            logger.debug("payload key %r not in schema; ignored", name)


def _choice_violations(schema: dict[str, Any], data: Any) -> list[str]:
    """Enforce x-soap-choice on the payload: at most one member per group,
    and exactly one when the group is required."""
    if not isinstance(data, dict):
        return []
    errors: list[str] = []
    for group in schema.get("x-soap-choice", []) or []:
        members = group.get("members", [])
        present = [m for m in members if data.get(m) is not None]
        if len(present) > 1:
            errors.append(
                f"at most one of {members} may be set (got {present})"
            )
        elif group.get("required") and not present:
            errors.append(f"exactly one of {members} is required")
    return errors


def build_envelope(op: dict[str, Any], payload: dict[str, Any],
                   index: _SpecIndex, options: BridgeOptions) -> bytes:
    xsoap = op["x-soap"]
    env_ns = SOAP_ENV_NS.get(xsoap.get("soapVersion", "1.1"), SOAP_ENV_NS["1.1"])
    nsmap = {"soapenv": env_ns}
    envelope = etree.Element(etree.QName(env_ns, "Envelope"), nsmap=nsmap)

    if options.auth == "wsse" and options.username is not None:
        header = etree.SubElement(envelope, etree.QName(env_ns, "Header"))
        security = etree.SubElement(
            header, etree.QName(WSSE_NS, "Security"), nsmap={"wsse": WSSE_NS}
        )
        security.set(etree.QName(env_ns, "mustUnderstand"), "1")
        token = etree.SubElement(security, etree.QName(WSSE_NS, "UsernameToken"))
        user = etree.SubElement(token, etree.QName(WSSE_NS, "Username"))
        user.text = options.username
        pwd = etree.SubElement(token, etree.QName(WSSE_NS, "Password"))
        pwd.set("Type", PASSWORD_TEXT)
        pwd.text = options.password or ""

    body = etree.SubElement(envelope, etree.QName(env_ns, "Body"))
    in_meta = xsoap.get("input", {})
    ns = in_meta.get("namespace")
    local = in_meta.get("element", xsoap.get("operation", "Request"))
    # use a *prefixed* namespace: unqualified children (rpc parts,
    # elementFormDefault="unqualified") must not inherit a default ns
    root_nsmap = {"tns": ns} if ns else None
    root = etree.SubElement(
        body, etree.QName(ns, local) if ns else local, nsmap=root_nsmap
    )
    _write_object(root, index.deref(op.get("input", {})), payload or {}, index)

    return etree.tostring(envelope, xml_declaration=True, encoding="utf-8")


# --------------------------------------------------------------------------
# SOAP response -> JSON
# --------------------------------------------------------------------------


def _localname(el: etree._Element) -> str:
    try:
        return etree.QName(el).localname
    except Exception:
        return str(el.tag)


def _coerce(text: str | None, schema: dict[str, Any]) -> Any:
    if text is None:
        return None
    t = schema.get("type")
    s = text.strip()
    try:
        if t == "integer":
            return int(s)
        if t == "number":
            return float(s)
        if t == "boolean":
            low = s.lower()
            if low in ("true", "1"):
                return True
            if low in ("false", "0"):
                return False
            return text  # non-canonical: don't silently coerce to False
    except ValueError:
        return text
    return text if t == "string" else (text if s == "" else s)


def _read_object(el: etree._Element, schema: dict[str, Any],
                 index: _SpecIndex) -> Any:
    schema = index.deref(schema)
    props: dict[str, Any] = schema.get("properties", {})
    if not props:
        # no schema knowledge: return text or shallow dict of children
        children = [c for c in el if isinstance(c.tag, str)]
        if not children:
            return el.text
        out: dict[str, Any] = {}
        for c in children:
            name = _localname(c)
            val = _read_object(c, {}, index)
            if name in out:
                if not isinstance(out[name], list):
                    out[name] = [out[name]]
                out[name].append(val)
            else:
                out[name] = val
        return out

    result: dict[str, Any] = {}
    children = [c for c in el if isinstance(c.tag, str)]
    by_name: dict[str, list[etree._Element]] = {}
    for c in children:
        by_name.setdefault(_localname(c), []).append(c)

    for name, pschema in props.items():
        pd = index.deref(pschema)
        xml = pd.get("xml") or (pschema.get("xml") if isinstance(pschema, dict) else None) or {}
        local = xml.get("name", name)
        if xml.get("attribute"):
            v = el.get(local)
            if v is not None:
                result[name] = _coerce(v, pd)
            continue
        if xml.get("x-text"):  # xsd:simpleContent text value
            result[name] = _coerce(el.text, pd)
            continue
        sub = pd.get("x-soap-substitution")
        items_schema = None
        if pd.get("type") == "array":
            items_schema = index.deref(pd.get("items", {}))
            sub = items_schema.get("x-soap-substitution") or sub
        if sub:
            # the wire carries the member element's own name; wrap it back
            # into the self-describing {"member": {...}} form
            entries = {m["element"]: m for m in sub.get("members", [])}
            found = [
                (_localname(c), c) for c in children
                if _localname(c) in entries
            ]
            wrapped = [
                {ln: _read_node(c, {"$ref": entries[ln]["schema"]}, index)}
                for ln, c in found
            ]
            if pd.get("type") == "array":
                result[name] = wrapped
            elif wrapped:
                result[name] = wrapped[0]
            continue
        nodes = by_name.get(local, [])
        if pd.get("type") == "array":
            result[name] = [_read_node(n, items_schema, index) for n in nodes]
        elif nodes:
            result[name] = _read_node(nodes[0], pd, index)
    return result


def _read_node(node: etree._Element, schema: dict[str, Any],
               index: _SpecIndex) -> Any:
    if node.get(etree.QName(XSI_NS, "nil")) in ("true", "1"):
        return None
    schema = index.deref(schema)
    if schema.get("type") == "object" or "properties" in schema:
        return _read_object(node, schema, index)
    return _coerce(node.text, schema)


def parse_fault(body: etree._Element, env_ns: str) -> dict[str, Any] | None:
    fault = body.find(f"{{{env_ns}}}Fault")
    if fault is None:
        return None
    if env_ns == SOAP_ENV_NS["1.2"]:
        code = fault.findtext(f"{{{env_ns}}}Code/{{{env_ns}}}Value") or ""
        reason = fault.findtext(f"{{{env_ns}}}Reason/{{{env_ns}}}Text") or ""
        detail_el = fault.find(f"{{{env_ns}}}Detail")
    else:
        code = fault.findtext("faultcode") or ""
        reason = fault.findtext("faultstring") or ""
        detail_el = fault.find("detail")
    detail = ""
    if detail_el is not None:
        detail = etree.tostring(detail_el, encoding="unicode")
    return {"faultcode": code, "faultstring": reason, "detail": detail}


def _http_error(http_status: int, content: bytes) -> tuple[int, dict[str, Any]]:
    return 502, {
        "faultcode": "spec2openapi.HTTPError",
        "faultstring": f"endpoint returned HTTP {http_status}",
        "detail": content[:2000].decode("utf-8", "replace"),
    }


def parse_response(content: bytes, op: dict[str, Any],
                   index: _SpecIndex,
                   http_status: int = 200) -> tuple[int, dict[str, Any]]:
    """Returns (mapped_status, json_payload). http_status is the transport
    status code, used to give sensible errors for empty/non-XML bodies."""
    xsoap = op["x-soap"]
    is_one_way = not xsoap.get("output")
    env_ns = SOAP_ENV_NS.get(xsoap.get("soapVersion", "1.1"), SOAP_ENV_NS["1.1"])

    if not content or not content.strip():
        # empty body: a one-way call with a 2xx succeeded; otherwise the
        # HTTP status carries the real story
        if http_status >= 400:
            return _http_error(http_status, content)
        if is_one_way:
            return 200, {}
        return 502, {
            "faultcode": "spec2openapi.EmptyResponse",
            "faultstring": f"endpoint returned an empty body (HTTP {http_status})",
            "detail": "",
        }
    try:
        # endpoint responses are untrusted: no entities, DTDs, or network
        parser = etree.XMLParser(resolve_entities=False, load_dtd=False,
                                 no_network=True, huge_tree=False)
        tree = etree.fromstring(content, parser=parser)
    except Exception as exc:
        if http_status >= 400:
            return _http_error(http_status, content)
        return 502, {
            "faultcode": "spec2openapi.InvalidXML",
            "faultstring": f"endpoint returned non-XML response: {exc}",
            "detail": content[:2000].decode("utf-8", "replace"),
        }
    body = tree.find(f"{{{env_ns}}}Body")
    if body is None:
        # tolerate the other soap version's namespace
        for alt in SOAP_ENV_NS.values():
            body = tree.find(f"{{{alt}}}Body")
            if body is not None:
                env_ns = alt
                break
    if body is None:
        if http_status >= 400:
            return _http_error(http_status, content)
        return 502, {
            "faultcode": "spec2openapi.NoBody",
            "faultstring": "no SOAP Body found in response",
            "detail": "",
        }

    fault = parse_fault(body, env_ns)
    if fault is not None:
        return 500, fault

    out_meta = xsoap.get("output") or {}
    expected = out_meta.get("element")
    root = None
    for c in body:
        if not isinstance(c.tag, str):
            continue
        if expected is None or _localname(c) == expected:
            root = c
            break
    if root is None:
        root = next((c for c in body if isinstance(c.tag, str)), None)
    if root is None:
        return 200, {}

    out_schema = index.deref(op.get("output", {}))
    data = _read_object(root, out_schema, index)
    if not isinstance(data, dict):
        data = {"value": data}
    return 200, data


# --------------------------------------------------------------------------
# the transport
# --------------------------------------------------------------------------


class SoapBridgeTransport(httpx.AsyncBaseTransport):
    """httpx transport that answers FastMCP's REST calls by calling SOAP."""

    def __init__(self, spec: dict[str, Any], options: BridgeOptions | None = None):
        self.index = _SpecIndex(spec)
        self.options = options or BridgeOptions.from_env()
        auth = None
        if self.options.auth == "basic" and self.options.username is not None:
            auth = (self.options.username, self.options.password or "")
        self._client = httpx.AsyncClient(
            auth=auth,
            timeout=self.options.timeout,
            verify=self.options.verify,
            headers=self.options.headers or {},
            trust_env=self.options.trust_env,
        )

    async def aclose(self) -> None:
        await self._client.aclose()

    def _json_response(self, request: httpx.Request, status: int,
                       payload: dict[str, Any]) -> httpx.Response:
        return httpx.Response(status, json=payload, request=request)

    async def handle_async_request(self, request: httpx.Request) -> httpx.Response:
        path = request.url.path
        op = self.index.ops.get(path)
        if op is None:
            return self._json_response(
                request, 404,
                {"faultcode": "spec2openapi.UnknownOperation",
                 "faultstring": f"no x-soap operation registered for path {path}",
                 "detail": ""},
            )
        raw = request.read()
        try:
            payload = json.loads(raw) if raw else {}
        except json.JSONDecodeError as exc:
            return self._json_response(
                request, 400,
                {"faultcode": "spec2openapi.BadRequest",
                 "faultstring": f"invalid JSON body: {exc}", "detail": ""},
            )

        xsoap = op["x-soap"]
        endpoint = self.options.endpoint or xsoap.get("endpoint")
        if not endpoint:
            return self._json_response(
                request, 502,
                {"faultcode": "spec2openapi.NoEndpoint",
                 "faultstring": "no SOAP endpoint configured "
                                "(x-soap.endpoint / SPEC2OPENAPI_ENDPOINT)",
                 "detail": ""},
            )

        violations = _choice_violations(
            self.index.deref(op.get("input", {})), payload
        )
        if violations:
            return self._json_response(
                request, 400,
                {"faultcode": "spec2openapi.ChoiceViolation",
                 "faultstring": "; ".join(violations), "detail": ""},
            )

        try:
            envelope = build_envelope(op, payload, self.index, self.options)
        except ValueError as exc:  # e.g. malformed substitution wrapper
            return self._json_response(
                request, 400,
                {"faultcode": "spec2openapi.BadRequest",
                 "faultstring": str(exc), "detail": ""},
            )
        action = xsoap.get("soapAction", "")
        if xsoap.get("soapVersion") == "1.2":
            ct = "application/soap+xml; charset=utf-8"
            if action:
                ct += f'; action="{action}"'
            headers = {"Content-Type": ct}
        else:
            headers = {
                "Content-Type": "text/xml; charset=utf-8",
                "SOAPAction": f'"{action}"',
            }

        try:
            soap_resp = await self._client.post(
                endpoint, content=envelope, headers=headers
            )
        except httpx.HTTPError as exc:
            return self._json_response(
                request, 502,
                {"faultcode": "spec2openapi.TransportError",
                 "faultstring": f"SOAP endpoint unreachable: {exc}", "detail": ""},
            )

        status, data = parse_response(
            soap_resp.content, op, self.index, soap_resp.status_code
        )
        return self._json_response(request, status, data)
