"""Optional MCP runtime glue (requires the [mcp] extra: fastmcp + httpx).

This module is a *reference implementation* showing how an openapi->MCP
runtime consumes specs generated by spec2openapi: FastMCP.from_openapi plus
the SOAP bridge transport that understands the x-soap extensions.

    mcp = spec2openapi.from_openapi_spec(spec2openapi.load_spec("spec.yaml"))
    mcp.run(transport="http", host="0.0.0.0", port=8000)
"""
from __future__ import annotations

import logging
from typing import Any

from .convert import convert_wsdl, load_spec, spec_has_soap  # noqa: F401
from .errors import MCP_HINT

logger = logging.getLogger("spec2openapi")

BRIDGE_BASE_URL = "http://spec2openapi.bridge.local"


def _spec_has_rest(spec: dict[str, Any]) -> bool:
    """True if any operation lacks x-soap (i.e. is a plain REST call).

    Built on openapi._operations, the single source of truth for "what is
    an operation" (#142): this used to filter to a hand-rolled method
    list that omitted 'trace', so a spec whose only operation was a
    non-SOAP 'trace' call was invisible here (a false "no REST operation"
    verdict, silently skipping the mixed-SOAP-and-REST warning below)."""
    from .openapi import _operations

    return any("x-soap" not in op for _, _, op in _operations(spec))

_MCP_HINT = (
    "the MCP runtime requires optional dependencies; "
    f"install them with: {MCP_HINT}"
)


def from_openapi_spec(
    spec: dict[str, Any],
    *,
    name: str | None = None,
    options: Any | None = None,
    validate_output: bool = False,
    **fastmcp_kwargs: Any,
):
    """OpenAPI dict -> FastMCP server.

    Specs containing x-soap operations are routed through the SOAP bridge;
    plain REST specs get a regular httpx client (one runtime serves both).
    """
    try:
        import httpx
        from fastmcp import FastMCP
    except ImportError as exc:  # pragma: no cover
        raise ImportError(_MCP_HINT) from exc

    from .bridge import BridgeOptions, SoapBridgeTransport, _client_kwargs

    if spec_has_soap(spec):
        if _spec_has_rest(spec):
            logger.warning(
                "spec contains both SOAP (x-soap) and plain REST operations; "
                "the reference runtime routes ALL traffic through the SOAP "
                "bridge, so the REST operations will not work. Split SOAP and "
                "REST specs until mixed specs are supported."
            )
        transport = SoapBridgeTransport(spec, options)
        client = httpx.AsyncClient(transport=transport, base_url=BRIDGE_BASE_URL)
    else:
        options = options or BridgeOptions.from_env()
        base = options.endpoint or (spec.get("servers") or [{}])[0].get("url", "")
        client = httpx.AsyncClient(base_url=base, **_client_kwargs(options))

    return FastMCP.from_openapi(
        openapi_spec=spec,
        client=client,
        name=name or spec.get("info", {}).get("title", "spec2openapi"),
        validate_output=validate_output,
        **fastmcp_kwargs,
    )


def from_wsdl(
    source: str,
    *,
    name: str | None = None,
    options: Any | None = None,
    validate_output: bool = False,
    **convert_kwargs: Any,
):
    """WSDL (path/URL) -> FastMCP server in one call."""
    spec = convert_wsdl(source, **convert_kwargs)
    return from_openapi_spec(
        spec, name=name, options=options, validate_output=validate_output
    )
