"""Optional MCP runtime glue (requires the [mcp] extra: fastmcp + httpx).

This module is a *reference implementation* showing how an openapi->MCP
runtime consumes specs generated by spec2openapi: FastMCP.from_openapi plus
the SOAP bridge transport that understands the x-soap extensions.

    mcp = spec2openapi.from_openapi_spec(spec2openapi.load_spec("spec.yaml"))
    mcp.run(transport="http", host="0.0.0.0", port=8000)
"""
from __future__ import annotations

import logging
from typing import Any

from .convert import convert_wsdl, load_spec, spec_has_soap  # noqa: F401

logger = logging.getLogger("spec2openapi")

BRIDGE_BASE_URL = "http://spec2openapi.bridge.local"

_MCP_HINT = (
    "the MCP runtime requires optional dependencies; "
    "install them with: pip install 'spec2openapi[mcp]'"
)


def from_openapi_spec(
    spec: dict[str, Any],
    *,
    name: str | None = None,
    options: Any | None = None,
    validate_output: bool = False,
    **fastmcp_kwargs: Any,
):
    """OpenAPI dict -> FastMCP server.

    Specs containing x-soap operations are routed through the SOAP bridge;
    plain REST specs get a regular httpx client (one runtime serves both).
    """
    try:
        import httpx
        from fastmcp import FastMCP
    except ImportError as exc:  # pragma: no cover
        raise ImportError(_MCP_HINT) from exc

    from .bridge import BridgeOptions, SoapBridgeTransport

    if spec_has_soap(spec):
        transport = SoapBridgeTransport(spec, options)
        client = httpx.AsyncClient(transport=transport, base_url=BRIDGE_BASE_URL)
    else:
        options = options or BridgeOptions.from_env()
        base = options.endpoint or (spec.get("servers") or [{}])[0].get("url", "")
        auth = None
        if options.auth == "basic" and options.username is not None:
            auth = (options.username, options.password or "")
        client = httpx.AsyncClient(
            base_url=base, auth=auth,
            timeout=options.timeout, verify=options.verify,
            headers=options.headers or {},
            trust_env=options.trust_env,
        )

    return FastMCP.from_openapi(
        openapi_spec=spec,
        client=client,
        name=name or spec.get("info", {}).get("title", "spec2openapi"),
        validate_output=validate_output,
        **fastmcp_kwargs,
    )


def from_wsdl(
    source: str,
    *,
    name: str | None = None,
    options: Any | None = None,
    validate_output: bool = False,
    **convert_kwargs: Any,
):
    """WSDL (path/URL) -> FastMCP server in one call."""
    spec = convert_wsdl(source, **convert_kwargs)
    return from_openapi_spec(
        spec, name=name, options=options, validate_output=validate_output
    )
